version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0

    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Lint javascript files
          command: yarn lint

      - run:
          name: Run tests
          command: yarn test
